[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Comment out if you don't have the edge source file
# [[edge_functions]]
# function = "shortener"
# path = "/i/*"

[[redirects]]
from = "/admin"
to = "/admin/"
status = 301

[[redirects]]
from = "/app"
to = "/app/"
status = 301
