[build]
  publish = "."

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# ── IMPORTANT: disable Edge Functions (no Deno needed)
# (We replace the edge mapping with a standard redirect to the Node function below)

# Route /i/* to the Node function netlify/functions/shortner.js
# NOTE: your repo shows "shortner.js" (no second 'e'); keep that spelling.
[[redirects]]
  from = "/i/*"
  to = "/.netlify/functions/shortner?path=:splat"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/app"
  to = "/app/"
  status = 301