[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_ENABLED = "false"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Function redirect (stays here)
[[redirects]]
  from = "/i/*"
  to = "/.netlify/functions/shortner?path=:splat"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/app"
  to = "/app/"
  status = 301
# Root goes straight to the dashboard
[[redirects]]
  from = "/"
  to = "/app/index.html"
  status = 200
