[build]
  publish = "."
  # (optional) if you build a frontend, set your build command here:
  # command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # (optional) include files if you read JSON/SQL/etc at runtime:
  # included_files = ["netlify/functions/**/assets/**"]

# --- Edge Function routing (SHORTENER) ---
[[edge_functions]]
  function = "shortener"
  path = "/i/*"

# --- Redirects (unchanged) ---
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/app"
  to = "/app/"
  status = 301