# --- Edge function route for short links like /i/abc123 ---
[[edge_functions]]
function = "shortener"
path = "/i/*"

# --- Functions bundling settings ---
[functions]
  node_bundler = "esbuild"   # Let esbuild bundle all deps (no external_node_modules)

# Keep your existing config below

# Ensure these folders are served as static pages (trailing slash)
[[redirects]]
from = "/admin"
to = "/admin/"
status = 301

[[redirects]]
from = "/app"
to = "/app/"
status = 301

# Convenience route to hit the test function
[[redirects]]
from = "/test-templates"
to = "/.netlify/functions/test-templates"
status = 200
force = true