[build]
  publish = "."

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[edge_functions]]
  function = "shortener"
  path = "/i/*"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/app"
  to = "/app/"
  status = 301