[build]
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "FALLBACK_USD_RATE,FX_USDNGN_FALLBACK"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/plugins/**,node_modules/**/doc/**,node_modules/**/CHANGELOG.md,node_modules/**/test/**,node_modules/**/*.d.ts"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[edge_functions]]
  function = "shortener"
  path = "/i/*"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/app"
  to = "/app/"
  status = 301