# --- Edge function route for short links like /i/abc123 ---
[[edge_functions]]
function = "shortener"
path = "/i/*"

# --- (Optional) Functions bundling settings ---
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios"]
# (keep your existing config)
# Ensure these folders are served as static pages
[[redirects]]
from = "/admin"
to = "/admin/"
status = 301

[[redirects]]
from = "/app"
to = "/app/"
status = 301

[[redirects]]
from = "/test-templates"
to = "/.netlify/functions/test-templates"
status = 200
force = true