# netlify.toml — full file

[build]
  command = "echo No build"
  publish = "."

# CORS (keep if you already had this)
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# Edge function will inspect host/path and only act on join.* or /_kv/*
[[edge_functions]]
  function = "shortener"
  path = "/*"

# Netlify KV: bind namespace "INVITES" for both edge + functions
[[kv_namespaces]]
  binding = "INVITES"
  id = "auto"