[build]
  command = ""
  publish = "app"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_ENABLED = "false"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/i/*"
  to   = "/.netlify/functions/shortner?path=:splat"
  status = 200

[[redirects]]
  from = "/"
  to   = "/index.html"
  status = 200

[[headers]]
  for = "/index.html"
  [headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"