# --- Functions bundling settings ---
[functions]
  directory = "netlify/functions"   # ← explicitly point to your functions
  node_bundler = "esbuild"          # bundle deps with esbuild

# If you DO NOT have netlify/edge-functions/shortener.* yet, comment this out.
# [[edge_functions]]
# function = "shortener"
# path = "/i/*"

# --- Basic build (static) ---
[build]
  publish = "."

# --- Redirects (keep yours) ---
[[redirects]]
from = "/admin"
to = "/admin/"
status = 301

[[redirects]]
from = "/app"
to = "/app/"
status = 301

[[redirects]]
from = "/test-templates"
to = "/.netlify/functions/test-templates"
status = 200
force = true